apiVersion: v1
kind: Service
metadata:
  name: {{ include "this.name" . }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range .Values.server.services}}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end}}
  selector:
    {{- include "this.selectorLabels" . | nindent 4 }}
