version: '3'

tasks:
  ############################################################
  default:
    desc: Run Build
    cmds:
      - task: server

  ############################################################
  server:
    desc: Build Server
    cmds:
      - go build -o bin/server ./cmd/server/main.go
