POST http://localhost:8000/v1/queue_job
Content-Type: application/json

{
  "image": "busybox",
  "command": ["sh", "-c", "echo Hello World && sleep 10"],
  "timeout": 120
}

###

POST http://localhost:8000/v1/delete_job
Content-Type: application/json

{
  "name": "spark-test-job"
}

###

POST http://localhost:8000/v1/get_job_logs
Content-Type: application/json

{
  "jobId": "spark-job-jukq7m0a7sgh12c"
}
