# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 1
restartPolicy: Always
# nodeSelector: {}
# tolerations: []
# affinity: {}
# imagePullSecrets: []

server:
  image:
    repository: ghcr.io/zcubbs/spark-server
    pullPolicy: IfNotPresent
    tag: "0.1.0"
  services:
    - name: gateway
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: grpc
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # Below are the placeholders for other configurations you may need.
  # Customize them according to your requirements.
  persistentVolume:
    enabled: false
    # accessModes:
    #   - ReadWriteOnce
    # size: 1Gi
    # storageClass: ""
    # existingClaim: ""
  # Security context for the pod
  securityContext:
    enabled: false
    # runAsUser: 1000
    # fsGroup: 2000
  # Configure environment variables for the container
  #  env: []

  # Configure readiness and liveness probes for the container
  livenessProbe:
    httpGet:
      path: /v1/ping
      port: gateway
    initialDelaySeconds: 15
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /v1/ping
      port: gateway
    initialDelaySeconds: 5
    periodSeconds: 10
  config: {}
web:
  image:
    tag: 0.1.0
